### ISSUE TITLE
作业内容无论你怎么布置都一样

### ISSUE THREAD

**Issue by tjw2003** [BJTU-SEPractice2023-III/HomeworkPlatformFrontend#13]
<img width="1244" alt="a4c5f518b43e9ecabf079f3e3d3e42a" src="https://github.com/BJTU-SEPractice2023-III/HomeworkPlatformFrontend/assets/114938661/4f0e17eb-4b4c-4cd6-89ea-e957b2f1416e">

**Comment by tjw2003** [comment]
都是这个东西

**Comment by AzurIce** [comment]
哦那个本来是这样的，用来把内容撑大测试换行的，待会删了就好了

**Comment by AzurIce** [comment]
这块：
https://github.com/BJTU-SEPractice2023-III/HomeworkPlatformFrontend/blob/38da825d13dec65cd47ce99bb6159a9f9f7ecfa3/src/pages/main/course/HomeworkDetail.tsx#L51-L53

**Comment by AzurIce** [comment]
Closed by #14
